### ISSUE TITLE
一些有关2.0的小bug

### ISSUE THREAD

**Issue by Litezero261** [SRInternet-Studio/Seewo-Custom_Start#2]
如题，我在使用你们的启动器时遇到了一些令人头疼的小bug,他们如下：
1.在使用一个过长的副标题时（如：ProUltraMaxEX）由于标签问题（我常使用易语言不知道这么说对不对）多余的字母会溢出到第二行中。
2.在用过一个长的副标题再改回短的副标题时（如：ProMaxUltra→Pro），主标题的对位不正确，会偏离中心位置。
3.当我在配置一个新的主题时，如果使用了已有主题的名称，程序将出现未响应现象。

**Comment by SRInternet** [comment]
首先，非常感谢你通过github进行的反馈，帮助我们更好地处理反馈的结果和跟进反馈动态。
其次，根据您提到的3点问题，我们给予以下回复：
1. 我们正在确认副标题所使用的 textblock 是否支持换行。如果确认问题的所在，我们会持续跟进，并给予您回复。
2. 通过您的文字描述，我们无法准确判断偏离的状况，希望您截图或附上视频再进行反馈哦
3. 我们在2.0中做了同源文件名的判断检测，对于您所描述的出现未响应的状况，我们无法判断问题的所在。希望您将事件查看器中，程序事件中的 .NET Runtime 错误事件截图并反馈噢
最后，欢迎您加入我们的qq交流群367798007与所有开发者和粉丝们进行互动和反馈以获得更快速的回复哦~
